export type Card = {
  emoji: string;
  name: string;
};

export const deck: Card[] = [
  { emoji: "🐓", name: "El Gallo" },
  { emoji: "🐷", name: "El Cerdo" },
  { emoji: "🐶", name: "El Perro" },
  { emoji: "😈", name: "El Diablito" },
  { emoji: "💁‍♀️", name: "La Dama" },
  { emoji: "🕴", name: "El Catrín" },
  { emoji: "🐱", name: "El Gato" },
  { emoji: "☔️", name: "El Paraguas" },
  { emoji: "🧜‍♀️", name: "La Sirena" },
  { emoji: "🪜", name: "La Escalera" },
  { emoji: "🍾", name: "La Botella" },
  { emoji: "🛢", name: "El Barril" },
  { emoji: "🌳", name: "El Arbol" },
  { emoji: "🍈", name: "El Melón" },
  { emoji: "🤺", name: "El Valiente" },
  { emoji: "🧢", name: "El Gorrito" },
  { emoji: "🪦", name: "La Muerte" },
  { emoji: "🍐", name: "La Pera" },
  { emoji: "🏁", name: "La Bandera" },
  { emoji: "🎸", name: "La Guitarra" },
  { emoji: "🎻", name: "El Violín" },
  { emoji: "🐦", name: "El Pájaro" },
  { emoji: "👋", name: "La Mano" },
  { emoji: "👢", name: "La Bota" },
  { emoji: "🌝", name: "La Luna" },
  { emoji: "🦜", name: "El Cotorro" },
  { emoji: "🥴", name: "El Borracho" },
  { emoji: "❤️", name: "El Corazón" },
  { emoji: "🍉", name: "La Sandía" },
  { emoji: "🥁", name: "El Tambor" },
  { emoji: "🏹", name: "El Arco" },
  { emoji: "👨‍🎤", name: "El Músico" },
  { emoji: "🕷", name: "La Araña" },
  { emoji: "⭐️", name: "La Estrella" },
  { emoji: "🥘", name: "El Cazo" },
  { emoji: "🌎", name: "El Mundo" },
  { emoji: "🌵", name: "El Nopal" },
  { emoji: "🦂", name: "El Alacrán" },
  { emoji: "🌹", name: "La Rosa" },
  { emoji: "💀", name: "La Calavera" },
  { emoji: "🔔", name: "La Campana" },
  { emoji: "🍶", name: "El Cantarito" },
  { emoji: "🦌", name: "El Venado" },
  { emoji: "🌞", name: "El Sol" },
  { emoji: "👑", name: "La Corona" },
  { emoji: "🛶", name: "La Canoa" },
  { emoji: "🌲", name: "El Pino" },
  { emoji: "🎣", name: "El Pescado" },
  { emoji: "🌴", name: "La Palma" },
  { emoji: "🪴", name: "La Maceta" },
  { emoji: "🐸", name: "La Rana" },
  { emoji: "🐊", name: "El Cocodrilo" },
  { emoji: "🦈", name: "El Tiburón" },
  { emoji: "🐢", name: "La Tortuga" },
  { emoji: "🦊", name: "El Zorro" },
  { emoji: "🐍", name: "La Serpiente" },
  { emoji: "🦅", name: "El Aguila" },
  { emoji: "🦋", name: "La Mariposa" },
  { emoji: "🍻", name: "La Cerveza" },
  { emoji: "💍", name: "El Anillo" },
];
